name: build

on:
    push:
        branches:
        - main

    workflow_dispatch:

defaults:
  run:
    shell: pwsh

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1

jobs:
  build:
    name: build-${{matrix.os}}

    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macOS-latest ]
        dotnet-version: [ '6.0.x', '8.0.x' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        dotnet-quality: 'ga'

#    - name: Install dependencies
#      run: dotnet restore

    - name: Build
      run: ./build compile
    # dotnet build --no-restore --configuration Release

    - name: Test
      run: ./build test
      # dotnet test --no-restore --configuration Release
